In [1]:
import csv
import Fitting_curves
from matplotlib import pyplot as plot
import numpy
from numpy import array

from Stepping_all import run_sim,get_results
import Fitting_module 
import Fitting_curves
from Fitting_curves import run_all_fits,get_initials,get_type
from Stepping_all import *
from Fitting_module import *
from steady_state_values import steady_state
import numpy
import scipy.optimize


In [2]:
tspan = numpy.linspace(0, 2000, 1000)
stepped_vars = Fitting_curves.stepped_var
output_vars = ['Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H']
data = Fitting_curves.data
types = Fitting_curves.fit_types
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]
yo_vals = Fitting_curves.yo_vals
simdata = get_results()
stepped_vars = ['Ps1','Ps2','Ps3','Cao','Tbo','F1']
outputs = ['Cc_measured', 'T', 'H']
names = []
for i, input in enumerate(stepped_vars):
    for j, output in enumerate(outputs):
        names.append(str(input) + str(output))
        
ss_values = steady_state()
ccss = ss_values['Cc']
tss = ss_values['T']
hss = ss_values['H']

        
data_sets = [data[key] for key in names]
fit_types = [get_type(name) for name in names]
yo_vals = [ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss]
initials = get_initials(fit_types)
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]

In [3]:
results = {'fit': ['Ps1Cc_measured',
  'Ps1T',
  'Ps1H',
  'Ps2Cc_measured',
  'Ps2T',
  'Ps2H',
  'Ps3Cc_measured',
  'Ps3T',
  'Ps3H',
  'CaoCc_measured',
  'CaoT',
  'CaoH',
  'TboCc_measured',
  'TboT',
  'TboH',
  'F1Cc_measured',
  'F1T',
  'F1H'],
 'initial': [[0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [-1, 0.5, 100, 100, 50],
  [-1, 0.5, 100, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 100, 50],
  [0.1, 100, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 50],
  [0.1, 100, 100, 50],
  [0.1, 100, 50]],
 'optimal_parameters': [array([ -1.38253997e-02,   1.61808000e+02,   1.38423046e+02]),
  array([  -0.23423524,  196.89551568,   35.34237873]),
  array([  1.11698206e-02,   5.05654067e+02,   1.77398533e+01]),
  array([ -1.11067301e+00,   1.43849445e-04,   2.21063319e+02,
           2.21063319e+02,   1.72888750e+02]),
  array([ -2.18683714e+01,   2.30110446e-01,   2.38583791e+02,
           2.38583791e+02,   7.07242426e+01]),
  array([ -1.09075194e-02,   3.41651167e+02,   4.32677094e+01]),
  array([ -2.83671300e-03,   6.15069734e+01,   6.15069734e+01,
           1.63317317e+02]),
  array([ -0.12562957,  56.52932092,  56.52932092,  44.43209789]),
  array([  6.16875297e-05,   3.03467861e+02,   7.11170954e+01]),
  array([   0.38383075,  190.66697563,  115.92429557]),
  array([  6.95708683,  82.93756092,  41.75555919]),
  array([ -8.39141854e-03,   4.32554018e+02,   3.53061530e+00]),
  array([  1.74916306e-02,   7.33523431e+01,   1.35525799e+02]),
  array([  0.96180938,  74.53602891,  22.40876107]),
  array([ -3.71108711e-04,   1.80724300e+02,   1.05344543e+02]),
  array([ 2640.59484704,   169.75746366,   132.09297316]),
  array([ 130.6625,  100.    ,  100.    ,   50.    ]),
  array([ 499.7268502 ,  429.50551286,    2.27720332])],
 'residuals': [array([  1.15788491e+00,   1.04169532e+02,   6.92857698e-01,
           6.15445750e-01,   2.59435684e+01,   4.67282223e-01,
           7.42190326e-01,   2.98027994e+01,   2.00992479e-02,
           3.40905668e+00,   5.50135747e+01,   6.55339933e-02,
           3.64700598e-01,   1.74999624e+01,   8.74606959e-02,
           2.69343774e+00,   6.64197438e+03,   1.22142706e+00])],
 'type': ['FOPTD',
  'FOPTD',
  'FOPTD',
  'SOZPTD',
  'SOZPTD',
  'FOPTD',
  'SOPTD',
  'SOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'FOPTD',
  'SOPTD',
  'FOPTD']}

In [4]:
tspan = numpy.linspace(0, 2000, 1000)
stepped_vars = Fitting_curves.stepped_var
output_vars = ['Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H']
data = Fitting_curves.data
types = Fitting_curves.fit_types
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]
yo_vals = Fitting_curves.yo_vals
simdata = get_results()

# getting data from fits
fitted = []

for i,fit in enumerate(results['fit']):
    parameters = results['optimal_parameters'][i]
    model = results['type'][i]
    u = u_vals[i]
    t = tspan
    yo = yo_vals[i]
    vals = Fitting_module.get_model_vals(parameters,model,u,t,yo)
    fitted.append(vals)




for i, name in enumerate(simdata.keys()):
    plot.figure()
    plot.plot(tspan,simdata[name],label = 'simulated')
    plot.plot(tspan,fitted[i],label='fitted')
    plot.title("Results of fitting a "+str(types[i]) + " model to step resonse of "+str(output_vars[i])+" to "+str(stepped_vars[i]))
    plot.axis()
    plot.legend(loc=1)
    plot.xlabel('Time in sec')
    plot.ylabel('value of output in SI units')

plot.show()

C:\Python34\lib\site-packages\scipy\signal\filter_design.py:1055: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)
C:\Users\Imberproninja\Desktop\Work\Honors\CBT\Project_Cstr\Simulation and modelling\CBT-project-CSTR-\System simulation\Steptesting and modelling\Code\Fitting_module.py:43: RuntimeWarning: overflow encountered in multiply
  x += dx * dt
C:\Users\Imberproninja\Desktop\Work\Honors\CBT\Project_Cstr\Simulation and modelling\CBT-project-CSTR-\System simulation\Steptesting and modelling\Code\Fitting_module.py:43: RuntimeWarning: invalid value encountered in add
  x += dx * dt


In [15]:
tspan = numpy.linspace(0, 2000, 1000)
stepped_vars = Fitting_curves.stepped_var
output_vars = ['Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H']
data = Fitting_curves.data
types = Fitting_curves.fit_types
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]
yo_vals = Fitting_curves.yo_vals
simdata = get_results()
stepped_vars = ['Ps1','Ps2','Ps3','Cao','Tbo','F1']
outputs = ['Cc_measured', 'T', 'H']
names = []
for i, input in enumerate(stepped_vars):
    for j, output in enumerate(outputs):
        names.append(str(input) + str(output))
        
ss_values = steady_state()
ccss = ss_values['Cc']
tss = ss_values['T']
hss = ss_values['H']

        
data_sets = [data[key] for key in names]
fit_types = [get_type(name) for name in names]
yo_vals = [ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss,ccss,tss,hss]
initials = get_initials(fit_types)
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]

In [6]:
names =  ['Ps3Cc_measured','Ps3T','TboH']

fit_types = ['SOPTD','SOPTD','SOPTD']
initials = [get_initials(fit_types)]
# initials[3][0] = 1
# initials[2][0] = -0.001
u_vals = [20,20,0.2 * 24]
#u_vals = [0.2 * 7.334e-4]
yo_vals = [ccss,tss,hss]
yo_vals =    [tss]

#initials[0] = [10000,100,0.5,50]
# initials[1][2] = 0.7
# initials[2][2] = 0.7

In [7]:
#print(prob_res['optimal_parameters'])
import csv
params = results['optimal_parameters']

# with open('fit_results.csv','wb') as csv_file:
#     writer = csv.writer(csv_file,delimiter = ',')
#     for i,fit in enumerate(params):
#         print(fit)
# #        csv_file.write(bytes(fit, 'UTF-8'))
#         writer.writerow(list(fit))

with open (r'Fit_results.csv', 'w', newline='') as write_file:
    write = csv.writer(write_file)
    write.writerows(fit for fit in params)

In [8]:
#u_vals = [20]#,20,0.2 * 24,0.2 * 7.334e-4]
u_vals = [0.2 * 7.334e-4]
types = fit_types
for i,fit in enumerate(prob_res['fit']):
    parameters = prob_res['optimal_parameters'][i]
    model = prob_res['type'][i]
    u = u_vals[i]
    t = tspan
    yo = yo_vals[i]
    vals = Fitting_module.get_model_vals(parameters,model,u,t,yo)
    fitted.append(vals)




for i, name in enumerate(prob_res['fit']):
    plot.figure()
    plot.plot(tspan,simdata[name],label = 'simulated')
    plot.plot(tspan,vals,label='fitted')
#    plot.title("Results of fitting a "+str(types[i]) + " model to step resonse of "+str(output_vars[i])+" to "+str(stepped_vars[i]))
    plot.axis()
    plot.legend(loc=1)
    plot.xlabel('Time in sec')
    plot.ylabel('value of output in SI units')

plot.show()

NameError: name 'prob_res' is not defined

In [ ]:
def SOPTD(parameters,u,tspan,yo):    # form is k/(t1s+1)(t2s+1)

    k,tau,zeta,theta = parameters

    G1 = lti([k], [tau**2,2*zeta*tau, 1])
    dt = tspan[1] - tspan[0]
    results = numpy.zeros(len(tspan))
    yvals = numpy.zeros(len(tspan))
    y = yo
    x = numpy.zeros([G1.A.shape[0], 1])

    for i, t in enumerate(tspan):
        yvals[i] = y
        t_interp = t - theta
        ydelayed = numpy.interp(t_interp, tspan, yvals)
        results[i] = ydelayed
        dx = G1.A.dot(x) + G1.B.dot(u)
        x += dx * dt
        y_prime = G1.C.dot(x) + G1.D.dot(u)
        y = y_prime[0][0] + yo

    return numpy.array(results)


In [11]:
from Fitting_module import SOPTD
data = SOPTD([-2.83658257e-03,   9.71055133e+01,   6.82392527e-01,
          1.34900330e+02],20,tspan,yo)

C:\Python34\lib\site-packages\scipy\signal\filter_design.py:1055: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)


In [12]:
plot.figure()
plot.plot(tspan,data)
plot.show()

In [ ]:
params

In [ ]:
with open('fit_results.csv','rb') as f:
    reader = csv.reader(f)
    all_params = list(reader)

In [ ]:
filename = 'fit_results.csv'
with open(filename, 'rU') as p:
    #reads csv into a list of lists
    my_list = [rec for rec in csv.reader(p, delimiter=',')]

In [ ]:
res = [map(list,i) for i in my_list]

In [ ]:
res = [list(i) for i in res]

In [ ]:
my_list = [[float(i) for i in my_list[j]] for j,lis in enumerate(my_list)]

In [ ]:
import csv
import Fitting_curves
from matplotlib import pyplot as plot
import numpy



# with open('fit_results.csv','rb') as f:
#     reader = csv.reader(f)
#     all_params = list(reader)
filename = 'fit_results.csv'
with open(filename, 'rU') as p:
    #reads csv into a list of lists
    my_list = [rec for rec in csv.reader(p, delimiter=',')]

all_params = [[float(i) for i in my_list[j]] for j,lis in enumerate(my_list)]

from Stepping_all import run_sim,get_results
import Fitting_module
names = Fitting_curves.names
tspan = numpy.linspace(0, 2000, 1000)
stepped_vars = Fitting_curves.stepped_var
output_vars = ['Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H','Cc_measured','T','H']
data = get_results()

types = Fitting_curves.fit_types
u_vals = [20,20,20,20,20,20,20,20,20,0.2*7.4,0.2*7.4,0.2*7.4,0.2*24,0.2*24,0.2*24,0.2*7.334e-4,0.2*7.334e-4,0.2*7.334e-4]
yo_vals = Fitting_curves.yo_vals
simdata = data

# getting data from fits
fitted = []

# for i,fit in enumerate(names):
#     parameters = all_params[i]
#     model = types[i]
#     u = u_vals[i]
#     t = tspan
#     yo = yo_vals[i]
#     vals = Fitting_module.get_model_vals(parameters,model,u,t,yo)
#     fitted.append(vals)




for i, name in enumerate(names):
    plot.figure()
    plot.plot(tspan,simdata[name],label = 'simulated')
#    plot.plot(tspan,fitted[i],label='fitted')
    plot.title("Results of fitting a "+str(types[i]) + " model to step resonse of "+str(output_vars[i])+" to "+str(stepped_vars[i]))
    plot.axis()
    plot.legend(loc=4)
    plot.xlabel('Time in sec')
    plot.ylabel('value of output in SI units')

plot.show()

In [33]:

from Fitting_curves import get_initials
data = data
names = ['Ps3Cc_measured']
types = ['SOPTD']
initials = get_initials(types)
dat = data['Ps3Cc_measured']
u_vals = [20]
yo_vals = [1.84]



res = run_all_fits(names,fit_types,initials,yo_vals,u_vals,dat)

Initializing
Running
current fit is 1 of 1


TypeError: list indices must be integers, not str

In [37]:
parameters

array([ 499.7268502 ,  429.50551286,    2.27720332])

[[-0.1, 100, 0.7, 50]]